name = "backend"
compatibility_date = "2023-12-01"

 [vars]
 DATABASE_URL="prisma://accelerate.prisma-data.net/?api_key=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJhcGlfa2V5IjoiZjA0OWE2ZjEtM2Q3MC00YjE1LThiMDEtMmYyYzg1YTUzZGZhIiwidGVuYW50X2lkIjoiNzM2M2YxNDg5MzE1NjQ4M2FkYzhmYTA3ZTc3NzBkYmZkMGVjZDkyNjRiY2QxZThhYjJiN2U0NmMwYzFjZmUyYSIsImludGVybmFsX3NlY3JldCI6IjBhZTRmM2RiLTkwYzEtNDAzMS1iYjUyLWQwN2Y0Mzc0YWNkNiJ9.Am8o8Fbjayv14nnQLNPoihK5ossvqLt1tYapfBOK8h4"
JWT_SECRET="aditya"


# MY_VAR = "my-variable"

# [[kv_namespaces]]
# binding = "MY_KV_NAMESPACE"
# id = "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx"

# [[r2_buckets]]
# binding = "MY_BUCKET"
# bucket_name = "my-bucket"

# [[d1_databases]]
# binding = "DB"
# database_name = "my-database"
# database_id = ""
